default_args:
  owner: 'Steam-Store-Games'
  retries: 1
  retry_delay: 5
dag_configs:
  - dag_id: "dbt_gold_trino"
    dag_type: "trino"
    schedule_interval: null
    max_actives_runs: 1
    start_date: "2025-05-05"
    catchup: false
    is_paused_upon_creation: false
    tasks:
      - task_id: dbt_run_gold
        script_path: "/opt/airflow/analytics_core"