version: 2

sources:
  - name: gold
    schema: steamgame
    tables:
      - name: steam
      - name: steam_requirements_data
      - name: steam_description_data
      - name: steam_media_data
      - name: steam_support_info
      - name: steamspy_tag_data