name: 'analytics_core'
version: '1.0.0'

profile: 'analytics_core'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
models:
  analytics_core:
    +materialized: view
    dim:
      +catalog: postgres_dw
      +materialized: table
    fact:
      +catalog: postgres_dw
      +materialized: table
    mart:
      +catalog: postgres_dw
      +materialized: table
