default_args:
  owner: 'Steam-Store-Games'
  retries: 1
  retry_delay: 5
dag_configs:
  - dag_id: "silver"
    dag_type: "transformation"
    schedule_interval: null
    max_actives_runs: 1
    start_date: "2025-05-05"
    catchup: false
    is_paused_upon_creation: false
    tasks:
      - task_id: silver_job
        script_path: "/opt/spark/src/transform/silver_job.py"